### PR TITLE
Fix check params tool

### PR DESCRIPTION
**Pull request by sasataku**
This PR fixes the issue of parameter check tool.

### CODE REVIEW

**Comment by yashi** [comment]
> The unit of the register values for the FPGA's XADC is currently set as unsigned int (mV), but in reality, it is float (V). This commit fixes it.

So, it was both wrong.  The type (uint vs float) and the unit (mV vs V).

**Comment by yashi** [comment]
This problem happend because the boundaries (`over` and `under`) are not with the data definitions (ex `main_tm.yaml`). IIRC, we use Python scripts to check the telemetry values because EPS telemetry is _variable-length and complex_.  Why are we checking _all_ component's telemetry variables with Python scripts?

**Comment by sasataku** [comment]
> we use Python scripts to check the telemetry values because EPS telemetry is variable-length and complex. Why are we checking all component's telemetry variables with Python scripts?

The telemetry of the EPS (including the GENERAL/STARTUP telemetry being checked this time) is of fixed length. These telemetry data are stored in the EPS storage; however, the telemetry format becomes variable-length when downlinking past telemetry in storage all at once.

**Comment by yashi** [comment]
Thanks but you ain't answering my question:

Why are we checking all component's telemetry variables with Python scripts?

**Comment by sasataku** [comment]
> Why are we checking all component's telemetry variables with Python scripts?

We have prepared a script for the following purposes:

1. To check the parameters (telemetry variables) obtained during the 1st pass without relying on visual inspection.
    (Of course, this script is not limited to use during the 1st pass only.)
2. Although alarms can be set, only the first detected value will be displayed.
3.  To export all parameters to a CSV file.

**Comment by yashi** [comment]
OK. This conversation started due to my misunderstanding. All scripts under `py/check/` is, at least for now, for and only for the first pass. Because we want to validate every single values of the first pass telemetory, we created these scripts. They have nothing to do with EPS at all.

The reason we don't use Yamcs's alarms is that we want list values and why the values ain't good.

**Pull request merged**
